import assert from 'node:assert/strict';
import * as THREE from 'three';
import { DEFAULT_OSNAP, findSmartSnap, mergeSnapSegments, projectMeshSnapSegments, calculateIntersectionSegments, referenceProfilesFromSegments, OSNAPSettings } from '../src/utils/snappingUtils';

const off: OSNAPSettings = Object.fromEntries(Object.keys(DEFAULT_OSNAP).map(k => [k, false])) as unknown as OSNAPSettings;
const line = { p1: { x: 10, y: 20 }, p2: { x: 50, y: 20 } };
const snap = (x: number, y: number, settings: Partial<OSNAPSettings>, anchor: { x: number; y: number }[] = []) => findSmartSnap(x, y, [], [line], anchor, { ...off, background: true, ...settings }, 1);
assert.equal(snap(30.2, 20.1, { midpoint: true }).type, 'midpoint');
assert.equal(snap(30.2, 20.1, { midpoint: true, background: false }).type, 'none');
assert.deepEqual(snap(32, 20.1, { nearest: true }).point, { x: 32, y: 20 });
assert.deepEqual(snap(22.1, 20.1, { perpendicular: true }, [{ x: 22, y: 40 }]).point, { x: 22, y: 20 });
assert.equal(snap(22.1, 20.1, { perpendicular: true }).type, 'none');
assert.deepEqual(snap(35, 40.1, { parallel: true }, [{ x: 22, y: 40 }]).point, { x: 35, y: 40 });
assert.equal(snap(10.1, 60, { vertex: true, guides: true }).point.x, 10);
assert.equal(findSmartSnap(30.1, 20.1, [], [line, { p1: { x: 30, y: 0 }, p2: { x: 30, y: 40 } }], [], { ...off, background: true, intersection: true }, 1).type, 'intersection');
const precise = { p1: { x: 1.123456, y: 2.234567 }, p2: { x: 8, y: 2.234567 } };
assert.equal(findSmartSnap(1.13, 2.23, [], [precise], [], { ...off, background: true, vertex: true }, 1).point.x, precise.p1.x);
const merged = mergeSnapSegments([{ p1: { x: 0, y: 0 }, p2: { x: 5, y: 0 } }, { p1: { x: 10, y: 0 }, p2: { x: 5, y: 0 } }]);
assert.equal(merged.length, 1);
assert.deepEqual(merged[0], { p1: { x: 0, y: 0 }, p2: { x: 10, y: 0 } });
const mesh = new THREE.Mesh(new THREE.BoxGeometry(40, 10, 30));
mesh.position.set(80, 5, 0);
const projected = projectMeshSnapSegments([mesh], 'XY');
assert.equal(projected.length, 4, 'Projected box has four feature edges, without triangle diagonals');
assert.equal(projectMeshSnapSegments([mesh], 'XZ').length, 4);
assert.equal(projectMeshSnapSegments([mesh], 'YZ').length, 4);
assert.equal(calculateIntersectionSegments([mesh], 'XY', 5).length, 4, 'Section fragments merge to complete edges');
assert.equal(calculateIntersectionSegments([mesh], 'XY', 50).length, 0);
assert.equal(projected.length, 4, 'Projection remains available outside the solid');
const profiles = referenceProfilesFromSegments(projected);
assert.equal(profiles.length, 1);
assert.deepEqual(findSmartSnap(80.1, 0.1, [], projected, [], { ...off, background: true, center: true }, 1, 5, profiles).point, { x: 80, y: 0 });
mesh.rotation.y = Math.PI / 4;
assert.equal(projectMeshSnapSegments([mesh], 'XY').length, 4, 'World rotation is respected');
const parent = new THREE.Group(); parent.add(mesh); parent.visible = false;
assert.equal(projectMeshSnapSegments([mesh], 'XY').length, 0, 'Hidden ancestors exclude references');
const circlePoints = Array.from({ length: 32 }, (_, i) => ({ x: 30 + 10 * Math.cos(i * Math.PI / 16), y: 40 + 10 * Math.sin(i * Math.PI / 16) }));
const circleEdges = circlePoints.map((p1, i) => ({ p1, p2: circlePoints[(i + 1) % 32] }));
const circles = referenceProfilesFromSegments(circleEdges);
assert.equal(circles[0].type, 'circle');
assert.ok(Math.abs(circles[0].center!.x - 30) < 1e-8);
const tangent = findSmartSnap(35.1, 48.7, circles, [], [{ x: 50, y: 40 }], { ...off, tangent: true }, 1);
assert.equal(tangent.type, 'tangent');
assert.ok(Math.abs(tangent.point.x - 35) < 1e-8);
assert.equal(findSmartSnap(10.1, 20.1, [], [line], [], off, 1).type, 'none');
mesh.geometry.dispose();
console.log('Snap references: projections, sections, transforms, centers, precision and selectable constraints passed.');
